services:
  # Serviço do PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: maiscargo_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-maiscargo}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/backup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - maiscargo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-maiscargo}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    command: postgres -c 'max_connections=50'

  # Serviço do Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: maiscargo_backend
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-postgres}
      - DB_NAME=${DB_NAME:-maiscargo}
      - DB_PORT=5432
      - PORT=${BACKEND_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development}
      - FRONTEND_URL=http://localhost:${FRONTEND_PORT:-5173}
      - JWT_SECRET=desenvolvimento_local_apenas
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - maiscargo_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Serviço do Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: maiscargo_frontend
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_PORT:-3000}/api
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - maiscargo_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
    name: maiscargo_postgres_data

networks:
  maiscargo_network:
    name: maiscargo_network
    driver: bridge 